import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "../style/globals.css";
import Navbar from "@/features/layout/components/Navbar";
import Footer from "@/features/layout/components/Footer";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  weight: ["100", "300", "400", "500", "700", "900"], // optional
  subsets: ["thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" className={notoSansThai.variable} >
      <body className={`${notoSansThai.variable} antialiased font-noto-sans-thai`} >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
