import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "../style/globals.css";

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  weight: ["100", "300", "400", "500", "700", "900"], // optional
  subsets: ["thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar(){
  
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSansThai.variable}>
      <body className={`${notoSansThai.variable} antialiased font-noto-sans-thai`} >
        {children}
      </body>
    </html>
  );
}
